######################################################################
# Automatically generated by qmake (2.01a) Tue Jul 10 00:20:21 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Messagebox.h
SOURCES += main.cpp Messagebox.cpp
