######################################################################
# Automatically generated by qmake (2.01a) Wed Jul 4 21:31:35 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . include sources
INCLUDEPATH += . include

# Input
HEADERS += include/button.h include/calculator.h
SOURCES += sources/button.cpp sources/calculator.cpp sources/main.cpp
