######################################################################
# Automatically generated by qmake (2.01a) Sun Jul 1 15:54:59 2018
######################################################################

TEMPLATE = app
TARGET = hello
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += hello.cpp
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets
