######################################################################
# Automatically generated by qmake (2.01a) Tue Jul 31 22:57:05 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += dialog.h
FORMS += dialog.ui
SOURCES += dialog.cpp main.cpp
