######################################################################
# Automatically generated by qmake (2.01a) Sun Jul 8 21:39:58 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += BuiltInDialog.h
SOURCES += BuiltInDialog.cpp main.cpp
