######################################################################
# Automatically generated by qmake (2.01a) Sat Jul 7 11:01:43 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mydialog.h
SOURCES += main.cpp mydialog.cpp
